language:
  - python
notifications:
  email:
    recipients:
      - ab.ioryz@gmail.com
    on_success: always
    on_failure: always
sudo: required
dist: trusty
env:
  matrix:
install:
  - sudo apt-get -qq update
  - sudo ./install.sh
  - ./python-install.sh
script:
  - ipython -c 'import sys; sys.exit()'
