complete -c gdrive -f -n '__fish_use_subcommand' -s 'c' -l 'config' -d 'Application path, default: /Users/<user>/.gdrive'
complete -c gdrive -f -n '__fish_use_subcommand' -l 'refresh-token' -d 'Oauth refresh token used to get access token (for advanced users)'
complete -c gdrive -f -n '__fish_use_subcommand' -l 'access-token' -d 'Oauth access token, only recommended for short-lived requests because of short lifetime (for advanced users)'
complete -c gdrive -f -n '__fish_use_subcommand' -l 'service-account' -d 'Oauth service account filename, used for server to server communication without user interaction (file is relative to config dir)'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'help' -d 'Print the help and exit'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'version' -d 'Print application version'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'list' -d 'List files'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'download' -d 'Download file or directory'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'upload' -d 'Upload file or directory'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'update' -d 'Update file, this creates a new revision of the file'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'info' -d 'Show file info'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'mkdir' -d 'Create directory'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'share' -d 'Share file or directory'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'delete' -d 'Delete file or directory'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'sync' -d 'List all syncable directories on drive'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'changes' -d 'List file changes'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'revision' -d 'revision'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'import' -d 'Upload and convert file to a google document, see "about import" for available conversions'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'export' -d 'Export a google document'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'about' -d 'Google drive metadata, quota usage'
complete -c gdrive -f -n '__fish_use_subcommand' -a 'help' -d 'Print help'

complete -c gdrive -f -n '__fish_seen_subcommand_from help' -l 'list' -l 'version' -l 'download' -l 'upload' -l 'update' -l 'info' -l 'mkdir' -l 'share' -l 'delete' -l 'sync'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -l 'no-header' -d 'Do not print the header'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -l 'absolute' -d 'Show absolute path to file (will only show path from first parent)'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -l 'bytes' -d 'Show file size as bytes'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -s 'm' -l 'max' -d 'Max files to list, default: 30'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -s 'q' -l 'query' -d 'Default query: "trashed = false and \'me\' in owners". See https://developers.google.com/drive/search-parameters'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -l 'order' -d 'Sort order. See https://godoc.org/google.golang.org/api/drive/v3#FilesListCall.OrderBy'
complete -c gdrive -f -n '__fish_seen_subcommand_from list' -l 'name-width' -d 'Width of name column, default: 40, minimum: 9, use 0 for full width'

complete -c gdrive -f -n '__fish_seen_subcommand_from download' -a 'query' -d 'Download all files and directories matching query'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -s 'f', -l 'force' -d 'Overwrite existing file'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -s 'r' -l 'recursive' -d 'Download directory recursively, documents will be skipped'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -l 'path' -d 'Download path'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -l 'delete' -d 'Delete remote file when download is successful'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -l 'no-progress' -d 'Hide progress'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -l 'stdout' -d 'Write file content to stdout'
complete -c gdrive -f -n '__fish_seen_subcommand_from download' -l 'timeout' -d 'Set timeout in seconds, use 0 for no timeout. Timeout is reached when no data is transferred in set amount of seconds, default: 300'
complete -c gdrive -f -n '__fish_seen_subcommand_from delete' -s 'r' -l 'recursive' -d 'Delete directory and all it\'s content'

complete -c gdrive -f -n '__fish_seen_subcommand_from upload' -a '-' -d 'Upload file from stdin'
complete -c gdrive -f -n '__fish_seen_subcommand_from share' -a 'list' -d 'List files permissions'
complete -c gdrive -f -n '__fish_seen_subcommand_from share' -a 'revoke' -d 'Revoke permission'
complete -c gdrive -f -n '__fish_seen_subcommand_from sync' -a 'list' -d 'List content of syncable directory'
complete -c gdrive -f -n '__fish_seen_subcommand_from sync' -a 'content' -d 'Sync drive directory to local directory'
complete -c gdrive -f -n '__fish_seen_subcommand_from sync' -a 'download' -d 'Revoke permission'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision' -a 'list' -d 'List file revisions'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision' -a 'download' -d 'Download revision'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision' -a 'delete' -d 'Delete file revision'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision delete' -s 'f' -l 'force' -d 'Overwrite existing file'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision delete' -l 'no-progress' -d 'Hide progress'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision delete' -l 'stdout' -d 'Write file content to stdout'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision delete' -l 'path' -d 'Download path'
complete -c gdrive -f -n '__fish_seen_subcommand_from revision delete' -l 'timeout' -d 'Set timeout in seconds, use 0 for no timeout. Timeout is reached when no data is transferred in set amount of seconds, default: 300'

complete -c gdrive -f -n '__fish_seen_subcommand_from about' -a 'import' -d 'Show supported import formats'
complete -c gdrive -f -n '__fish_seen_subcommand_from about' -a 'export' -d 'Show supported export formats'
